name: ci

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Linux Tester
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@0267444136ce4919088f5eae0461f736f21356de
      - run: cargo test --workspace
  format:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@0267444136ce4919088f5eae0461f736f21356de
        with:
          components: rustfmt
      - name: run rustfmt
        uses: actions-rust-lang/rustfmt@862c67d86b6bfbc9c63de2f866638cab2f11ecbc
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@0267444136ce4919088f5eae0461f736f21356de
        with:
          components: clippy
      - name: run clippy
        run: cargo clippy --workspace
